badges/urls.py
from django.conf.urls import url

from badges import views

urlpatterns = [
    url(r'^$', views.overview, name="badges_overview"),
    url(r'^(?P<slug>[A-Za-z0-9_-]+)/$', views.detail, name="badge_detail"),
]

badges/models.py
from __future__ import unicode_literals
from datetime import datetime

from django.contrib.auth import get_user_model
try:
    from django.urls import reverse
except ImportError:
    from django.core.urlresolvers import reverse
from django.db import models
from django.conf import settings

from badges.signals import badge_awarded
from badges.managers import BadgeManager

if hasattr(settings, 'BADGE_LEVEL_CHOICES'):
    LEVEL_CHOICES = settings.BADGE_LEVEL_CHOICES
else:
    LEVEL_CHOICES = (
        ("1", "Bronze"),
        ("2", "Silver"),
        ("3", "Gold"),
        ("4", "Diamond"),
    )

class Badge(models.Model):
    id = models.CharField(max_length=255, primary_key=True)
    user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="badges", through='BadgeToUser')
    level = models.CharField(max_length=1, choices=LEVEL_CHOICES)

    icon = models.ImageField(upload_to='badge_images')

    objects = BadgeManager()

    @property
    def meta_badge(self):
        from .utils import registered_badges
        return registered_badges[self.id]

    @property
    def title(self):
        return str(self.meta_badge.title)

    @property
    def description(self):
        return self.meta_badge.description

    def __unicode__(self):
        return "%s" % self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('badge_detail', kwargs={'slug': self.id})

    def award_to(self, user):
        has_badge = self in user.badges.all()
        if self.meta_badge.one_time_only and has_badge:
            return False

        BadgeToUser.objects.create(badge=self, user=user)

        badge_awarded.send(sender=self.meta_badge, user=user, badge=self)

        return BadgeToUser.objects.filter(badge=self, user=user).count()

    def number_awarded(self, user_or_qs=None):
        """
        Gives the number awarded total. Pass in an argument to
        get the number per user, or per queryset.
        """
        kwargs = {'badge':self}
        if user_or_qs is None:
            pass
        elif isinstance(user_or_qs, get_user_model()):
            kwargs.update(dict(user=user_or_qs))
        else:
            kwargs.update(dict(user__in=user_or_qs))
        return BadgeToUser.objects.filter(**kwargs).count()


class BadgeToUser(models.Model):
    badge = models.ForeignKey(Badge, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created = models.DateTimeField(default=datetime.now)


from . import listeners

badges/views.py
from django.shortcuts import render, get_object_or_404

from .models import Badge

def overview(request, extra_context={}):
    badges = Badge.objects.active().order_by("level")
    
    context = locals()
    context.update(extra_context)
    return render(request, "badges/overview.html", context)

def detail(request, slug, extra_context={}):
    badge = get_object_or_404(Badge, id=slug)
    users = badge.user.all()
    
    context = locals()
    context.update(extra_context)
    return render(request, "badges/detail.html", context)

badges/templates/badges/badge.html
{% comment %}
	This is the html for displaying an individual badge on the site. It expects that
	you will pass it a badge object called "badge".

	Here is an example:
	<div class="badges">
		{% for badge in user_profile.user.badges.all %}
			{% include "badges/badge.html" %}
		{% endfor %}
	</div>

{% endcomment %}

<a href="{{ badge.get_absolute_url }}" title="{{ badge.title }} ({{ badge.get_level_display }}): {{ badge.description }}">
	<span class="level_{{ badge.level}} metal">●</span> {{ badge.title }}
</a>

badges/templates/badges/badges_display.html
{% comment %}
	This template is for displaying the badges a user has earned next to their name. It 
	expects that you will pass it a list of badge objects called badges.

	Here is an easy way to do that:

	{% with badges as post.user.badges %}
		{% include "badges/badges_display.html %}
	{% endwith %}

{% endcomment %}



{% load badges_tags %}
<span class="badge">
{% for level in u|badge_count %}
	{% if level.count %}
		<span title="{{level.count}} {{level.badge__level|level_title}} badge{{level.count|pluralize}}"><span class="level_{{level.badge__level}} metal">●</span>{{level.count}}</span>
	{% endif %}
{% endfor %}
</span>

badges/templates/badges/detail.html
{% extends "badges/overview.html" %}
{% load badges_tags %}
{% load humanize %}

{% block body %}
<div id="badges_tank">
	<h1>{% block head_title %}Badge: {{ badge.title }}{% endblock %}</h1>
    <p class="info_blurb">{{ badge.description }}</p>
	<ul class="users">
		{% for u in users %}
			<li><a href='{{ u.get_absolute_url }}'>{{ u.username }}</a></li>
		{% empty %}
			<li>Nobody has earned this badge!</li>
		{% endfor %}
    </ul>
</div>
{% endblock %}

badges/templates/badges/overview.html
{% extends "site_base.html" %}
{% load badges_tags %}
{% load humanize %}

{% block body %}
<div id="badges_tank">
	<h1>{% block head_title %}Badges{% endblock %}</h1>
	<p class="info_blurb"><strong>Post</strong> images, predictions, and tutorials, <strong>respond</strong> to posts, and <strong>vote</strong> for helpful, informative or clever responses — Otaku Pride will reward you with badges along the way! Here is a list of the badges, and how many people have earned each one.</p>
	<p class="info_blurb">Badges are fun! They're just little reminders that <strong>you are awesome</strong> <span class="faces">☺</span></p>
	<table class="badges">
		{% for badge in badges %}
		<tr class="{% cycle 'highlighted' '' %}">
			<td class="checkmarks">
				{% if badge|is_in:request.user.badges.all %}<span title="You have earned this badge">✔</span>{% endif %}&nbsp;
			</td>
			<td class="badge">
				{% include "badges/badge.html" %}
				× {{ badge.user.count|intcomma }}
			</td>
			<td class="badge_description">{{ badge.description }}</td>
		</tr>
		{% endfor %}
	</table>
</div>
{% endblock %}

{% block rightColumn %}
	<h3>The Badge System</h3>
		<p>A way for us to say thank you. A way to let others know you care. A way to show your contributions to the community. 
		<br/><br/>
		A way to shake your money maker.
		</p><br/>
		<p>Bronze Badges are given for completing basic tasks.</p><br/>
		<p>Silver Badges are given for being an active part of the community.</p><br/>
		<p>Gold Badges are given for going above the role of active participation. Given for being on the ball, into the latest and greatest, and popular.</p>
		
{% endblock %}